data_path: "/home/lianzhao/deep-contact-estimator/data/csv/sequence_data.npy"
label_path: "/home/lianzhao/deep-contact-estimator/data/csv/sequence_data_label.npy"
mat_data_path: "/home/justin/data/contact_data/test_sequence/mat/lcmlog-2021-02-21-5-short_network_data.mat"
model_load_path: "/home/lianzhao/deep-contact-estimator/model/model_best_val_loss.pt"

# data params
window_size: 150

# network params
batch_size: 1

calculate_accuracy: True

save_mat: False
mat_save_path: "/home/justin/code/deep-contact-estimator/inference_results/0914_5-short_network_data.mat"

save_lcm: False
lcm_save_path: "/home/justin/code/deep-contact-estimator/inference_results/0914_5-short_network_data.lcm"
