data_path: "/home/justin/data/archive_contact_data/test_sequence/numpy/lcmlog-2021-06-05_09_network_data.npy"
label_path: "/home/justin/data/archive_contact_data/test_sequence/numpy/lcmlog-2021-06-05_09_network_data_label.npy"
mat_data_path: "/home/justin/data/archive_contact_data/test_sequence/mat/lcmlog-2021-06-05_09_network_data.mat"
model_load_path: "/home/justin/code/deep-contact-estimator/results/0616_2blocks_best_val_loss.pt"

# data params
window_size: 150

# network params
batch_size: 1

calculate_accuracy: False

save_mat: True
mat_save_path: "/home/justin/code/deep-contact-estimator/inference_results/lcmlog-2021-06-05_09_network_data.mat"

save_lcm: True
lcm_save_path: "/home/justin/code/deep-contact-estimator/inference_results/lcmlog-2021-06-05_09_network_data.lcm"