# This file saves parameter that you need to modify accordingly in order to run the lcm-cnn interface

model_name: "0730_2blocks_best_val_loss.onnx"
data_name: "input_matrix_500Hz.bin"
# program_path: "/media/jetson256g/code/LCM_CNN_INTERFACE/deep-contact-estimator/"
program_path: "/home/tingjun/Desktop/mini_cheetah/deep-contact-estimator/"

# 500Hz version:
# engine_save_path: "/media/jetson256g/code/LCM_CNN_INTERFACE/deep-contact-estimator/engines/0730_2blocks_best_val_loss.trt"
# engine_load_path: "/media/jetson256g/code/LCM_CNN_INTERFACE/deep-contact-estimator/engines/0730_2blocks_best_val_loss.trt"
engine_save_path: "/home/tingjun/Desktop/mini_cheetah/deep-contact-estimator/engines/0730_2blocks_best_val_loss.trt"
engine_load_path: "/home/tingjun/Desktop/mini_cheetah/deep-contact-estimator/engines/0730_2blocks_best_val_loss.trt"

input_h: 75
input_w: 54
output_size: 16
mode: "normal" # normal is 500 Hz, fast is 1000 Hz

# 1000Hz version:
# engine_save_path: "/media/jetson256g/code/LCM_CNN_INTERFACE/deep-contact-estimator/engines/0616_2blocks_best_val_loss.trt"
# engine_load_path: "/media/jetson256g/code/LCM_CNN_INTERFACE/deep-contact-estimator/engines/0616_2blocks_best_val_loss.trt"

# input_h: 150
# input_w: 54
output_size: 16
# mode: "fast" # normal is 500 Hz, fast is 1000 Hz

lcm_leg_channel: "leg_control_data"
lcm_imu_channel: "microstrain"
lcm_contact_gt_channel: "contact_ground_truth"
lcm_output_channel: "synced_proprioceptive_data"

leg_q_dimension: 12
leg_qd_dimension: 12
leg_p_dimension: 12
leg_v_dimension: 12
leg_tau_dimension: 12

imu_acc_dimension: 3
imu_omega_dimension: 3
imu_rpy_dimension: 3
imu_quat_dimension: 4

num_legs: 4

debug_flag: 1 # 1 for enable debugging mode, 0 for disable