mat_folder: "/home/lianzhao/deep-contact-estimator/data/mat/"
save_path: "/home/lianzhao/deep-contact-estimator/data/numpy/"

csv_path: "/home/lianzhao/deep-contact-estimator/data/csv/"
csv_save_path: "/home/lianzhao/deep-contact-estimator/data/csv/"

# mode: "train": split data into train/val/test
#       "inference": create numpy for one seq without spliting
#       "mat2lcm": simply convert mat to lcm
mode: "train"

# contact_type: "GRF":
#               "gait_cycle"
#               "contact"
contact_type: "contact"
mat_data_path: "/home/lianzhao/deep-contact-estimator/data/mat/lcmlog-2020-08-29-00_network_data.mat"
lcm_save_path: "/home/lianzhao/deep-contact-estimator/data/lcm/lcmlog-2020-08-29-00_network_data_automatic_contact.lcm"

window_size: 150
train_ratio: 0.7
val_ratio: 0.15
