
mat_folder: "/home/justin/data/contact_data/terrain_type_train/mat/"
save_path: "/home/justin/data/contact_data/terrain_type_train/numpy/"

# mode: "train": split data into train/val/test
#       "inference": create numpy for one seq without spliting
mode: "train"

train_ratio: 0.7
val_ratio: 0.15
