
mat_folder: "/home/neofelis/cheetah/Cheetah Data/contact_data/500Hz/mat/"
save_path: "/home/neofelis/cheetah/Cheetah Data/contact_data/500Hz/test_sequence/numpy/"

# mode: "train": split data into train/val/test
#       "inference": create numpy for one sequence without spliting
mode: "train"

train_ratio: 0.7
val_ratio: 0.15
