
data_folder: "/home/justin/data/contact_data/numpy/"
model_save_path: "/home/justin/code/deep-contact-estimator/results/0308_stacked_test.weight"
loss_history_path: "/home/justin/code/deep-contact-estimator/results/0308_stacked_test_loss_history.npy"

print_every: 1000

# data params
window_size: 300

# network params
batch_size: 30
init_lr: 0.00005
lr_decay_rate: 0.97
num_epoch: 300


