data_folder: "/home/justin/data/cassie_contact_data/2021-08-20_contact_data_in_FRB/test_spring_numpy/"
model_load_path: "/home/justin/code/deep-contact-estimator/results/0822_cassie_spring_contact_best_val_loss.pt"

# data params
window_size: 800

# network params
batch_size: 30

save_to_mat: False
mat_save_path: "/home/justin/code/deep-contact-estimator/results/0822_cassie_spring_contact_best_val_loss.mat"

