data_folder: "/home/justin/data/contact_data/numpy/"
model_load_path: "/home/justin/code/deep-contact-estimator/results/0316_ws150_lr1e-4_2block_drop_out_best_val_acc.pt"

# data params
window_size: 150

# network params
batch_size: 30

save_to_mat: False
mat_save_path: "/home/justin/code/deep-contact-estimator/results/0316_ws150_lr1e-4_2block_drop_out_best_val_acc.mat"

